server:
  name: go-mongo-layer-architecture-sample
  port: 8080

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

log:
  level: info
  map:
    time: "@timestamp"
    msg: message
    stacktrace: stacktrace
    caller: caller
    function: func

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
  status: status

response:
  id: X-Response-Id
  correlation: X-Correlation-Id
